services:
  kaikaio-server:
    image: kaikaioano/kaikaio-server:branch-master
    # image: kaikaio-server:latest
    container_name: kaikaio-server
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - PORT=4000
      - MONGO_URI=host.docker.internal:27017/KaiKaiBlog
    restart: unless-stopped
    mem_limit: 512m